// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA-Z7QK_dNb_5BN4Hj-Wdg3nDk3Crb42Y',
    appId: '1:920605013319:web:d46ada82cddee96372c862',
    messagingSenderId: '920605013319',
    projectId: 'pizza-paradise-eb3c1',
    authDomain: 'pizza-paradise-eb3c1.firebaseapp.com',
    storageBucket: 'pizza-paradise-eb3c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9fNJ4va9y_WR3cWPpMuyqqEskKaqFlG4',
    appId: '1:920605013319:android:6c1ee44edd5f746d72c862',
    messagingSenderId: '920605013319',
    projectId: 'pizza-paradise-eb3c1',
    storageBucket: 'pizza-paradise-eb3c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuTYRI6c1ASNS3gwc-_gk0tDKTDjKFCVM',
    appId: '1:920605013319:ios:a4d28950b1c2ac0172c862',
    messagingSenderId: '920605013319',
    projectId: 'pizza-paradise-eb3c1',
    storageBucket: 'pizza-paradise-eb3c1.appspot.com',
    iosClientId: '920605013319-v0q52slfmf2jdoue0vuo1gkiq89n6208.apps.googleusercontent.com',
    iosBundleId: 'com.example.pizzaParadise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuTYRI6c1ASNS3gwc-_gk0tDKTDjKFCVM',
    appId: '1:920605013319:ios:a4d28950b1c2ac0172c862',
    messagingSenderId: '920605013319',
    projectId: 'pizza-paradise-eb3c1',
    storageBucket: 'pizza-paradise-eb3c1.appspot.com',
    iosClientId: '920605013319-v0q52slfmf2jdoue0vuo1gkiq89n6208.apps.googleusercontent.com',
    iosBundleId: 'com.example.pizzaParadise',
  );
}
